### ISSUE TITLE
Generating powerpoint with linked data file

### ISSUE THREAD

**Issue by mohsinhere** [GemBoxLtd/GemBox.Presentation.Examples#1] opened 2020-10-26 06:45 UTC
I'm trying to generate a PowerPoint based on an existing template. The template has charts with underlying data where I can right-click on the chart and edit data.

When I generate pptx file using Gembox and then right-click on the chart to edit data, it says "The linked file isn't available. This error can occur if the linked file has been moved or hasn't been saved. Embedding the data instead of linking it can help avoid this error, but the data won't update automatically if it changes in the source file".

**Comment by mario-gembox** [comment] 2020-10-26 07:01
Hi,

Can you please send us a small VS project that reproduces your issue so that we can investigate it?

Regards,
Mario

**Comment by mario-gembox** [comment] 2020-10-28 05:55
Or can you perhaps just send us your template file?

**Comment by mohsinhere** [comment] 2020-10-28 22:47
Apologies for the delayed response... I was on leave the past 2 days... I'll send the template file and sample project to your info@ address.

**Comment by mohsinhere** [comment] 2020-10-29 00:38
@gemboxsoftware-dev-team  I have now sent the template via email.

Below is the sample code that I used:

```
        static void Main(string[] args)
        {
            //setting free licenses
            ComponentInfo.SetLicense("FREE-LIMITED-KEY");
            SpreadsheetInfo.SetLicense("FREE-LIMITED-KEY");

            Console.WriteLine("Generating powerpoint");
            LoadFromExistingTemplate();

        }

        private static void LoadFromExistingTemplate()
        {
            var presentation = PresentationDocument.Load(@"C:\Local Dev\Matter description.pptx");

            //retrieve first slide
            var slide = presentation.Slides[0];

            var shape = slide.Content.Drawings
                .OfType<Shape>()
                .First(item => item.Placeholder?.PlaceholderType == PlaceholderType.Title);

            if (shape.Name == "Title 3")
            {
                shape.Text.Paragraphs[0].Elements.Clear();
                shape.Text.Paragraphs[0].AddRun("Project Magenta");
            }

            var date = slide.Content.Drawings.OfType<Shape>()
                .FirstOrDefault(x => x.Name == "Text Placeholder 5");

            date?.Text.Paragraphs[0].TextContent.Replace("[date]", DateTime.Now.ToString("d MMM yyyy").ToUpper());

            //formatting charts (progress bar)
            //var headerChart = slide.Content.Drawings.OfType<GraphicFrame>().FirstOrDefault(x => x.Name == "Chart 34");

            //var excelSheet = (BarChart)headerChart?.Chart.ExcelChart;

            //if (excelSheet != null)
            //{
            //    excelSheet.Worksheet.Rows[1].Cells[3].Value = 400000;
            //    excelSheet.Worksheet.Rows[1].Cells[1].Value = 70700;
            //}


            presentation.Save(@"C:\Local Dev\Test1.pptx");
        }
```

**Comment by mario-gembox** [comment] 2020-10-29 09:13
I just tried using the latest bugfix versions for both GemBox.Presentation and GemBox.Spreadsheet and was unable to reproduce this issue.
I'll send you the "Test1.pptx" file that I get to your address.

**Comment by mario-gembox** [comment] 2020-11-10 10:29
After the investigation, it was concluded that the problem was with the Excel table that was the source of the chart's data in the PPTX file.
This issue is now resolved with the latest bugfix version, available on the [BugFixes](https://www.gemboxsoftware.com/spreadsheet/downloads/bugfixes.html) page and [NuGet](https://www.nuget.org/packages/GemBox.Spreadsheet/).

**Closed as completed by mario-gembox** 2020-11-10 10:29 UTC
Labels: bug
